### PR TITLE
Add more resource import support

### PR DESCRIPTION
**Pull request by bmhughes**
Add import support for most resources

### CODE REVIEW

**Comment by bdwyertech** [comment]
Cool stuff, thanks for this!  Looks like you fixed a few other things as well.

This is marked as a WIP -- would you like me to merge/release?  Looks good to me.

**Comment by bmhughes** [comment]
> Cool stuff, thanks for this! Looks like you fixed a few other things as well.
> 
> This is marked as a WIP -- would you like me to merge/release? Looks good to me.

No problem, I've just converted this back to a draft as I've realised I've let a commit in I shouldn't have. 

I was experimenting with storing empty attributes as `nil` rather than empty JSON strings but it didn't work out with how the chef server API works but I've noticed the defaults for environment attributes are still set to `nil`. I'll remove that and mark this as ready again when I've sorted it.

**Comment by bmhughes** [comment]
Should be good now

**Comment by bdwyertech** [comment]
Looks like the changes in how it sets the ID for node and chef environment broke the tests.  I'll revert and fix next week.  That's what I get from merging a PR from the beach ⛱️

**Comment by jimwise** [comment]
I think there's still an issue here -- I can't import a node if the node's `name` is not the same as it's `id` (working with an environment where the chef node names are the fqdn, so not a valid resource id).

**Pull request merged**
